title: Susan Currie Sivek
description: Writing, editing, and content portfolio
author: Susan Currie Sivek
email: susan.sivek@gmail.com

plugins:
  - jekyll-redirect-from

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - scripts
  - Gemfile
  - Gemfile.lock
  - vendor
  - _plugins

